# Generated by Django 2.2.4 on 2019-09-04 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='地区编号')),
                ('Name', models.CharField(default='全国', max_length=5, verbose_name='地区名字')),
            ],
        ),
        migrations.CreateModel(
            name='BBSSection',
            fields=[
                ('Sid', models.AutoField(primary_key=True, serialize=False, verbose_name='版块编号')),
                ('SName', models.CharField(default='', max_length=10, verbose_name='版块名称')),
                ('SStatement', models.CharField(default='', max_length=200, verbose_name='版块说明')),
                ('SClickCount', models.PositiveSmallIntegerField(default=0, verbose_name='版块总点击次数')),
                ('SRepCount', models.PositiveSmallIntegerField(default=0, verbose_name='板块总回复数')),
                ('STopicCount', models.PositiveSmallIntegerField(default=0, verbose_name='版块主贴数')),
            ],
        ),
        migrations.CreateModel(
            name='CompClass',
            fields=[
                ('Cid', models.AutoField(primary_key=True, serialize=False, verbose_name='类别编号')),
                ('CName', models.CharField(default='未设置', max_length=10, verbose_name='类别名称')),
                ('CStatement', models.CharField(max_length=100, null=True, verbose_name='类别说明')),
                ('CCount', models.PositiveSmallIntegerField(default=0, verbose_name='该类别下赛事数量')),
            ],
        ),
        migrations.CreateModel(
            name='CompInfo',
            fields=[
                ('Iid', models.AutoField(primary_key=True, serialize=False, verbose_name='赛事编号')),
                ('IName', models.CharField(default='', max_length=60, verbose_name='赛事名称')),
                ('IApplyStartTime', models.DateField(verbose_name='报名开始时间')),
                ('IApplyEndTime', models.DateField(verbose_name='报名结束时间')),
                ('IOrganizers', models.CharField(default='', max_length=100, verbose_name='主办单位')),
                ('IObject', models.TextField(default='（空）', verbose_name='参赛对象')),
                ('IMethods', models.TextField(default='（空）', verbose_name='参赛方法')),
                ('ISchedule', models.TextField(default='（空）', verbose_name='赛程信息')),
                ('IStatement', models.TextField(default='（空）', verbose_name='赛事介绍')),
                ('Iurls', models.URLField(default='', verbose_name='赛事官网')),
                ('IAreaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Area', verbose_name='赛事地区编号')),
                ('IClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CompClass', verbose_name='竞赛类别编号')),
            ],
        ),
        migrations.CreateModel(
            name='CompRecord',
            fields=[
                ('RID', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('RTitle', models.CharField(default='', max_length=60, verbose_name='记录标题')),
                ('RStatement', models.CharField(default='', max_length=100, verbose_name='记录简要说明')),
                ('RTime', models.DateField(auto_now_add=True, verbose_name='发布日期')),
                ('RClickCount', models.PositiveSmallIntegerField(default=0, verbose_name='点击数')),
                ('RMarkCount', models.PositiveSmallIntegerField(default=0, verbose_name='收藏人数')),
                ('RClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CompClass', verbose_name='赛事类别编号')),
                ('RContentID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.CompInfo', verbose_name='赛事内容编号')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UBirthday', models.DateField(blank=True, null=True, verbose_name='用户生日')),
                ('USex', models.CharField(blank=True, default='保密', max_length=2, null=True, verbose_name='用户性别')),
                ('UStatement', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='用户个人说明')),
                ('nickname', models.CharField(blank=True, default='', max_length=10, verbose_name='用户昵称')),
                ('UPostCount', models.PositiveSmallIntegerField(default=0, verbose_name='用户发帖数')),
                ('URepCount', models.PositiveSmallIntegerField(default=0, verbose_name='用户回帖数')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarkMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MarkTime', models.DateField(auto_now_add=True, verbose_name='收藏时间')),
                ('CompRecordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CompRecord', verbose_name='记录编号')),
                ('UsersId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserMessage', verbose_name='用户编号')),
            ],
        ),
        migrations.AddField(
            model_name='comprecord',
            name='RMarkUser',
            field=models.ManyToManyField(related_name='MarkUser_set', through='backend.MarkMessage', to='backend.UserMessage', verbose_name='收藏者'),
        ),
        migrations.AddField(
            model_name='comprecord',
            name='RPromulgatorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Promulgator_set', to='backend.UserMessage', verbose_name='发布者编号'),
        ),
        migrations.CreateModel(
            name='BBSTopic',
            fields=[
                ('Tid', models.AutoField(primary_key=True, serialize=False, verbose_name='主帖编号')),
                ('TReplyCount', models.PositiveSmallIntegerField(default=0, verbose_name='主帖回复次数')),
                ('TTopic', models.CharField(default='', max_length=50, verbose_name='主帖标题')),
                ('TContents', models.TextField(max_length=1500, null=True, verbose_name='主帖内容')),
                ('TClickCount', models.PositiveSmallIntegerField(default=0, verbose_name='主帖点击次数')),
                ('TTime', models.DateField(auto_now_add=True, verbose_name='发帖时间')),
                ('TLastClickT', models.DateField(verbose_name='主帖最后点击时间')),
                ('TSid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.BBSSection', verbose_name='主帖版块编号')),
                ('TUid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserMessage', verbose_name='主帖用户编号')),
            ],
        ),
        migrations.AddField(
            model_name='bbssection',
            name='SClassId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CompClass', verbose_name='比赛类别编号'),
        ),
        migrations.CreateModel(
            name='BBSReply',
            fields=[
                ('Rid', models.AutoField(primary_key=True, serialize=False, verbose_name='回贴编号')),
                ('RTime', models.DateField(auto_now_add=True, verbose_name='回复时间')),
                ('RContent', models.TextField(default='', max_length=500, verbose_name='回复内容')),
                ('RLevelNum', models.PositiveSmallIntegerField(default=0, verbose_name='在主贴中对应楼层')),
                ('RSid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.BBSSection', verbose_name='板块编号')),
                ('RTid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.BBSTopic', verbose_name='主贴编号')),
                ('RUid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserMessage', verbose_name='回复者用户编号')),
            ],
        ),
    ]
