# Generated by Django 2.2 on 2019-10-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbsreply',
            name='RTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='回复时间'),
        ),
        migrations.AlterField(
            model_name='bbstopic',
            name='TLastClickT',
            field=models.DateTimeField(verbose_name='主帖最后点击时间'),
        ),
        migrations.AlterField(
            model_name='bbstopic',
            name='TTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发帖时间'),
        ),
        migrations.AlterField(
            model_name='compinfo',
            name='IAreaID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.Area', verbose_name='赛事地区编号'),
        ),
        migrations.AlterField(
            model_name='comprecord',
            name='RTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布日期'),
        ),
    ]
