# Generated by Django 2.2.4 on 2019-09-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='nickname',
            new_name='Unickname',
        ),
        migrations.RenameField(
            model_name='usermessage',
            old_name='User',
            new_name='UserBase',
        ),
    ]
