# Generated by Django 2.2.4 on 2019-10-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191021_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='test11',
            name='testImg',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='test11',
            name='name',
            field=models.CharField(max_length=3),
        ),
    ]
