# Generated by Django 2.2 on 2019-10-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191021_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test11',
            name='testImg',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
    ]
